### PR TITLE
Added control options (increase/decrease volume and mute)

### PR DESCRIPTION
**Pull request by AviusX**

### CODE REVIEW

**Comment by MarcDonald** [comment]
Hey, thanks for this it seems super useful! There's just two small sticking points I found

* I get this warning when attempting to run the script (happens with all the actions like `inc-vol` and `dev-vol`):
image
but it doesn't seem to affect script functionality and goes away when I comment out the `break;` statements.

* The `pactl` commands seem to require an index rather than just the name so the old syntax with the `MICROPHONE_NAME` argument such as `click-left = bash PATH_TO_SCRIPT inc-vol MICROPHONE_NAME` doesn't work for the control commands, you get this error:
image
unless you use the actual index
image

Again, thanks for submitting this PR, if these issues can be resolved I'll merge it in :smile_cat:

**Comment by AviusX** [comment]
Hi! Sorry about those break statements haha. I guess it's a bad habit that carried over from other languages. I keep forgetting they're not required in shell. Removed them.

As for the pactl command not taking the device name, that sounds wrong. The man page says that the device may be identified by either its numerical index or the symbolic name-
image

And the command seems to be working as expected with the name on mine.-
image

(tried it with a couple different devices using names just to be sure it was working as expected.)

May I ask what version of pactl you're using? Mine is 14.2 which is probably the newest stable one since I'm on arch. I should also mention that the name of the device I'm using is the name mentioned in `pacmd list-sources`.
image

**Comment by MarcDonald** [comment]
I'm using `pactl 13.99.1` but I think the reason is that for the original `show-vol` I grepped for just a part of the name which is why it works with just `Meteor` when the actual full name is `alsa_input.usb-Samson_Technologies_Samson_Meteor_Mic-00.analog-stereo`, is there any way to do this with the `pactl` commands? If not it's not a big deal and I can just update the Readme to mention that it needs the full name.

The commands all work as expected when I use the full `alsa_input.usb-Samson_Technologies_Samson_Meteor_Mic-00.analog-stereo` name

**Comment by AviusX** [comment]
Ah I see. I don't know of a way to do this without the full name. At least not using `pactl` itself. It might be possible to implement some hacky way to do this but that kinda sounds like a pain.

We could just use `pacmd` to adjust volume but that doesn't take percentages and doesn't have the `+ -` functionality to increase or decrease volume. We'd have to calculate it. So `pacmd set-source-volume 5 30000` sets the volume to around 42% on mine. It'll probably work with the device name like `pacmd set-source-volume 'Meteor' 30000`. This is also a super hacky way imo, so maybe just mention that it requires the full device name in the readme if you're okay with it.

Also, I just discovered that there is a `@DEFAULT_SOURCE@` arg that automatically picks the default source in the `pactl` command which seems like a cleaner approach than grepping for the default source index-
image

Let me know if you want this implemented. But it should also be noted that while this does seem like a cleaner approach, we're already grepping for the index and the device for fetching the volume using `pacmd` so it might just be redundant. If they change the output of `pacmd` we'll have to change the script anyway, regardless of whether we use `@DEFAULT_SOURCE@` or not.

**Comment by MarcDonald** [comment]
> This is also a super hacky way imo, so maybe just mention that it requires the full device name in the readme if you're okay with it

I agree, I'll do a commit to this PR with an update to the Readme now.

I think with regards to the default source we should just leave it as it is just so we have one place where the default is determined, just to avoid confusion when reading through the code.

Again, thanks for the PR, I'll merge it in once I update the Readme :smiley:

**Comment by AviusX** [comment]
Np and thank you for the merge as well! I guess this would count as my first official "open source contribution" then haha :smile:

**Pull request merged**
